[gcp_service_account]
type = "service_account"
project_id = "interstatdashboard"
private_key_id = "97dba5301de92bd4af040147bbb4f14d44df376b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRXF9FF+f2rC7B
34TDQRKi8ZnWt7g1wpVDgiKQtHifVAQ9g6Knx7r674w8F8BIZuomsTDtr4MIaZNH
dyw1CzhpEIxlC+f2rPELVGmnj3kr4YJkZ6PzKcHjJH70WGLcgnRgtdnd0sN6ih5Z
23YePeJMbyr7IHz7towXKT2YmhTjz8dOiBxbBxklQea7G6+FX/o8aOmE0Je5P5/B
dMxWVASWzZAmR7EvZyggMORZUhgIf39HvgQUDfVEIfYIl5KO1H6dmdTHOZ4yUQuV
ydU+cUkxPsFltMXuCE/xQtjdXY7Wf+19M5StGhMYPPft+tRI2jRkWhtN+voFkYHW
iBLAIHhpAgMBAAECggEABriY7hqsHs94zP2PB7EtUavuo0s04QV5fdjZTMwPbLyH
gqmgvnXBe0NSvl+RxDc/+eCFBORx4FRzWyFTQbOeXNtHRo/Nnq4B6jZxuS3s2h7P
9uEE52QloyFHnngswAnnJCacZ4GMiNC0lQ6M8FqHqWWVfO2UYdYftZ1yS+lJ8HuT
2wj/1q4JaHZKQP52KV1eoLnicoxLVjaA1rwV/PZmEDbY2Fzj4wbNTqMQpMW5wtCo
mmde7dMeTeFA8iSCCGfb3Z8XZn91wyLyaUu9VbzLGmYNJMOYD8UXWzbyEOu11q8F
U4a8wW2c0cSMO75oQA4hDlco9D9CP1Qylv+OiEhyhQKBgQDMSrJ7zHXVQbWuilUT
FD6mNVs3OSltbSFzXP2Qi+XN5FeP0zfZX9IVT114/RCMNtamze/uUH0zO8xhkEox
6kFu0YmwJM+VTHPK+FDRW6j1cjFMi6wkBizr5xI8OKZ7cmd9o5eiqb7gjSps3mFE
A4DBaBNpuPYdoz/tBRVHiCjVnQKBgQC2Jy5dUM0HRgPpWGaK4mrOfxnDPWBWVSu/
2xrwmR+/0ndDcskyBeNRQLCsfPuHgcoC8Y9Jg3Ck4vesIi1i7mDQhawoTUTHDrxS
W1pr/XfEMjARtQgpUeOzmHPLDmDMWd0sHO9+rpGwLWTJLCSJPbFijm6WF1sd7yzR
T7xf5gA6PQKBgCJHon19iIQ5W3gnRDFIY17WczDoCZiQCF3oS7AWmYAcAcljguqZ
1pG22JN1u3IbvZcN1WXi4a9YKGpyoNCRY1tqE7WX57FAu+liE4Wd4NMWz0jt4vvE
gYMwKfIq+1yZjN4bNlWYMCxT47uS8TVNdSx+/0rtO3crro1iHfj70wZNAoGAPyDb
H7oWJJQuXNunRjDsJT7FdfW6gpEoBWjxMDtRVpChhr2sXurNemZ6FH2IStE/ar+/
EhI8otiKT5zUr/m/keUR4jHNSVOhDsXcU5rXvCZMpIZiGrfnu2F1mAUWpRvr3BL3
KadklHNW/6WN0AaSiH6mctwLVxeCJ9SDi5TRtV0CgYB04Cbp9kWqoUH5giUaAp/1
+BsWHmddnvzAjPL6fhimNmMjfX5UZutB7o/z5Yaiv9MNKwtqxrFh2HwSVjXvGMiL
czbKSKR+kFEbNoQQuiyKiXZkzT2eW/3PCBvlcU1G+f0+U+9uyO+7ebLkX6aNNdxG
VYamqxQy8U3F+q275q76BA==
-----END PRIVATE KEY-----"""
client_email = "interfootballstat@interstatdashboard.iam.gserviceaccount.com"
client_id = "117328312126044872950"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/interfootballstat%40interstatdashboard.iam.gserviceaccount.com"

[spreadsheet_ids]
default = { id = "1yKtKwtmQheGPvIpBcus-BbkbTc5WcF_J91uVVXOe5Zk", name = "Main Stats Sheet" }
sheet2 = { id = "your_second_sheet_id", name = "Another Stats Sheet" }
sheet3 = { id = "your_third_sheet_id", name = "Extra Stats" }